//! `gen-profiles`: a directory of source printer profiles read into the shipped
//! catalogue. What it may take from the source and what it may not invent is in
//! `docs/design/profiles.md`.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::Parser;
use printer_profiles::{PrinterProfile, is_valid_id};

use crate::cross_check::MachineList;
use crate::ini::Ini;
use crate::machine::{Machine, Transcribed, transcribe};

/// The line that marks a catalogue file as this generator's to rewrite. A file without it
/// was written by hand and is left alone.
const MARKER: &str = "# Generated by `cargo xtask gen-profiles`";

#[derive(Parser)]
pub struct Args {
    /// Directory of source profiles, one `.ini` per machine.
    #[arg(long)]
    source: PathBuf,
    /// Where the printer catalogue is written.
    #[arg(long, default_value = "assets/profiles/printers")]
    out: PathBuf,
    /// A published machine list to check every transcribed panel against.
    #[arg(long)]
    cross_check: Option<PathBuf>,
    /// Report what would change and write nothing.
    #[arg(long)]
    dry_run: bool,
}

/// What one run did, printed at the end so a diff can be reviewed against it.
#[derive(Default)]
struct Report {
    written: Vec<String>,
    kept: Vec<String>,
    waiting: Vec<String>,
    adjudicated: Vec<String>,
    refused: Vec<String>,
}

pub fn run(args: &Args) -> Result<()> {
    let list = args
        .cross_check
        .as_deref()
        .map(MachineList::load)
        .transpose()?;
    let mut report = Report::default();

    for source in sources(&args.source)? {
        let stem = source
            .file_stem()
            .and_then(|stem| stem.to_str())
            .with_context(|| format!("{} has no readable name", source.display()))?;
        match one(stem, &source, args, list.as_ref()) {
            Ok(Outcome::Written { id, over_the_list }) => {
                if let Some(reason) = over_the_list {
                    report.adjudicated.push(format!("{id}: {reason}"));
                }
                report.written.push(id);
            }
            Ok(Outcome::Kept(id)) => report.kept.push(id),
            Ok(Outcome::Waiting(step)) => report.waiting.push(format!("{stem}: {step}")),
            Err(error) => report.refused.push(format!("{stem}: {error:#}")),
        }
    }

    for stale in stale(&args.out, &report.written)? {
        report
            .refused
            .push(format!("{stale}: no longer in the source"));
    }
    report.print(args.dry_run);
    if report.refused.is_empty() {
        Ok(())
    } else {
        bail!("{} machines were refused", report.refused.len())
    }
}

enum Outcome {
    /// Written out, with the reason the published list was overruled where it was.
    Written {
        id: String,
        over_the_list: Option<&'static str>,
    },
    Kept(String),
    Waiting(&'static str),
}

fn one(stem: &str, source: &Path, args: &Args, list: Option<&MachineList>) -> Result<Outcome> {
    let ini = Ini::load(source)?;
    let machine = match transcribe(stem, &ini)? {
        Transcribed::Waiting(step) => return Ok(Outcome::Waiting(step)),
        Transcribed::Ready(machine) => machine,
    };
    if !is_valid_id(&machine.id) {
        bail!("`{}` is not a usable catalogue id", machine.id);
    }

    let target = args.out.join(format!("{}.toml", machine.id));
    if target.exists() && !is_generated(&target)? {
        return Ok(Outcome::Kept(machine.id));
    }
    let over_the_list = match list {
        Some(list) => check(&machine, list)?,
        None => None,
    };
    let text = render(&machine)?;
    PrinterProfile::from_toml_str(&text, &target)
        .with_context(|| format!("the generated profile for {} does not load", machine.id))?;
    if !args.dry_run {
        std::fs::write(&target, &text)
            .with_context(|| format!("cannot write {}", target.display()))?;
    }
    Ok(Outcome::Written {
        id: machine.id,
        over_the_list,
    })
}

/// Where the published machine list disagrees with the source profile and the source is
/// the one to believe. Each line is a judgement made once, with what settles it.
const LIST_IS_STALE: [(&str, &str); 2] = [
    (
        "elegoo-mars-4-dlp",
        "a 1440p projector; the list carries its LCD sibling's 4098 x 2560 panel",
    ),
    (
        "prusa-sl1s-speed",
        "the list swaps the panel's millimetres while keeping its pixels, which makes the pixel non-square",
    ),
];

/// Holds a transcribed machine against the published list, unless the two were already
/// adjudicated in favour of the source.
fn check(machine: &Machine, list: &MachineList) -> Result<Option<&'static str>> {
    if let Some((_, reason)) = LIST_IS_STALE
        .iter()
        .find(|(id, _)| *id == machine.id.as_str())
    {
        return Ok(Some(reason));
    }
    if let Some(difference) = list.disagreement(&machine.profile) {
        bail!("the machine list disagrees: {difference}");
    }
    if !list.lists(&machine.profile) {
        bail!("the machine list does not carry this machine");
    }
    Ok(None)
}

/// One catalogue file: the header that says where the numbers came from, then the profile.
fn render(machine: &Machine) -> Result<String> {
    let profile = &machine.profile;
    let mut text = format!(
        "# {} {}.\n#\n{MARKER}; change the generator, not this file.\n#\n\
         # UNVERIFIED: these numbers are transcribed from a published machine\n\
         # specification, not measured. Check them against the actual machine before\n\
         # trusting a print, especially the illuminated area and the mirroring flags.\n",
        profile.manufacturer, profile.name
    );
    if machine.older_revision {
        text.push_str(
            "#\n# The source profile asks for a `.ctb` below version 4 and we write\n\
             # version 4, so this machine needs firmware from 2021 or later. An older\n\
             # board refuses the file rather than misprinting it.\n",
        );
    }
    text.push('\n');
    text.push_str(&toml::to_string_pretty(profile).context("the profile does not serialise")?);
    Ok(text)
}

fn is_generated(path: &Path) -> Result<bool> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("cannot read {}", path.display()))?;
    Ok(text.contains(MARKER))
}

/// Every `.ini` under the source directory, in a fixed order so two runs report the same.
fn sources(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
        .with_context(|| format!("cannot read {}", dir.display()))?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "ini"))
        .collect();
    if files.is_empty() {
        bail!("{} holds no .ini profile", dir.display());
    }
    files.sort();
    Ok(files)
}

/// Generated catalogue files this run did not produce, which means the source dropped the
/// machine. They are reported rather than deleted, so removing one stays a reviewed edit.
fn stale(out: &Path, written: &[String]) -> Result<Vec<String>> {
    let mut stale = Vec::new();
    for entry in std::fs::read_dir(out).with_context(|| format!("cannot read {}", out.display()))? {
        let path = entry?.path();
        if path.extension().is_none_or(|extension| extension != "toml") {
            continue;
        }
        let Some(id) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        if !written.iter().any(|written| written == id) && is_generated(&path)? {
            stale.push(id.to_owned());
        }
    }
    stale.sort();
    Ok(stale)
}

impl Report {
    fn print(&self, dry_run: bool) {
        let verb = if dry_run { "would write" } else { "wrote" };
        println!("{verb} {} machines", self.written.len());
        Self::list("waiting on a later step", &self.waiting);
        Self::list(
            "taken from the source over the published list",
            &self.adjudicated,
        );
        Self::list("kept, written by hand", &self.kept);
        Self::list("refused", &self.refused);
    }

    fn list(title: &str, lines: &[String]) {
        if lines.is_empty() {
            return;
        }
        println!("\n{} {title}:", lines.len());
        for line in lines {
            println!("  {line}");
        }
    }
}
