//! The `run.gcode` program: the settings header a slicer reads back and the per-layer
//! block the board executes. Every key and every line is in `docs/formats/gcode-zip.md`.

use core_format::PrintJob;
use core_raster::Shading;

/// What names us in the header, which a reader shows and a machine ignores.
const SLICER: &str = concat!("Encrust-", env!("CARGO_PKG_VERSION"));

/// The comment a reader takes the writing software's name from.
pub(crate) const GENERATED_BY: &str = ";Generated by ";

/// The whole program but the per-layer blocks: the settings header and the opening moves.
pub(crate) fn preamble(job: &PrintJob) -> String {
    let mut text = format!("{GENERATED_BY}{SLICER}\n");
    text.push_str(&header(job));
    text.push_str(
        "\n;START_GCODE_BEGIN\n\
         G21;Set units to be mm\n\
         G90;Absolute positioning\n\
         M17;Enable motors\n\
         M106 S0;Turn LED OFF\n\
         ;<Slice> Blank\n\
         G28 Z0;Home Z\n\
         ;END_GCODE_BEGIN\n",
    );
    text
}

/// The settings header, `;key:value` a line, in the order a vendor file carries them.
fn header(job: &PrintJob) -> String {
    let (printer, material, display) = (&job.printer, &job.material, &job.printer.display);
    let mirrored = printer.mirror_x || printer.mirror_y;
    let mut head = Header::default();

    // The archive names its layers by number, so nothing in it refers to the file's own
    // name and a vendor file leaves this empty too.
    head.text("fileName", "");
    head.text("machineType", printer.machine_name());
    head.number("estimatedPrintTime", job.print_time_s() as f32);
    head.number("volume", job.volume_mm3 / 1000.0);
    head.text("resin", &material.name);
    head.number("weight", job.weight_g());
    head.number("price", job.cost().unwrap_or_default());
    head.number("layerHeight", job.nominal_height_mm());
    head.int("resolutionX", job.raster.width_px);
    head.int("resolutionY", job.raster.height_px);
    head.number("machineX", display.width_mm);
    head.number("machineY", display.height_mm);
    head.number("machineZ", printer.build_volume.z);
    head.text(
        "projectType",
        if mirrored { "LCD_mirror" } else { "Normal" },
    );
    head.number("normalExposureTime", job.header_exposure_s());

    // Two keys for the bottom exposure and two for the bottom count: a reader takes
    // whichever its generation of the firmware wrote, so both carry the same value.
    head.number("bottomLayExposureTime", material.bottom_exposure_s);
    head.number("bottomLayerExposureTime", material.bottom_exposure_s);

    head.number("normalDropSpeed", material.retract_speed_mm_min);
    head.number("normalLayerLiftSpeed", material.lift_speed_mm_min);
    head.number("normalLayerLiftHeight", material.lift_distance_mm);
    head.number("zSlowUpDistance", 0.0);
    head.int("bottomLayCount", material.bottom_layers);
    head.int("bottomLayerCount", material.bottom_layers);

    // How the panel is mounted, not what the masks were drawn as, as in every other
    // container we write (ADR 0134).
    head.int("mirror", u32::from(mirrored));

    head.int("totalLayer", job.layer_count());
    head.number("bottomLayerLiftHeight", material.bottom_lift_distance_mm);
    head.number("bottomLayerLiftSpeed", material.bottom_lift_speed_mm_min);
    head.number("bottomLightOffTime", material.light_off_s());
    head.number("lightOffTime", material.light_off_s());
    head.int("bottomPWMLight", u32::from(material.bottom_light_pwm));
    head.int("PWMLight", u32::from(material.light_pwm));
    head.int(
        "antiAliasLevel",
        match job.raster.shading {
            Shading::Coverage => 8,
            Shading::Binary => 1,
        },
    );
    head.finish()
}

/// One layer's block: the image to show, the peel around it and the exposure itself.
///
/// Everything here is this layer's own, which is why the container carries a banded
/// exposure and a stack of mixed thicknesses that the other archive cannot (ADR 0167).
pub(crate) fn layer_block(job: &PrintJob, index: u32) -> String {
    let material = &job.material;
    let bottom = material.is_bottom_layer(index);
    let z_mm = job.layer_z_mm(index);
    let [before_lift_s, after_lift_s, after_retract_s] = material.waits.rests_s();
    // A bottom layer comes back down from exactly where it went, as in every other
    // container: the profile states no bottom retract distance of its own.
    let (lift_mm, lift_speed, retract_mm, retract_speed) = if bottom {
        (
            material.bottom_lift_distance_mm,
            material.bottom_lift_speed_mm_min,
            material.bottom_lift_distance_mm,
            material.bottom_retract_speed_mm_min,
        )
    } else {
        (
            material.lift_distance_mm,
            material.lift_speed_mm_min,
            material.retract_distance_mm,
            material.retract_speed_mm_min,
        )
    };
    let pwm = if bottom {
        material.bottom_light_pwm
    } else {
        material.light_pwm
    };

    let mut block = format!(
        ";LAYER_START:{index}\n;PositionZ:{z}mm\nM6054 \"{image}\";Show image\n",
        z = mm(z_mm),
        image = image_name(index),
    );
    let mut line = |text: String| block.push_str(&text);

    wait(&mut line, before_lift_s, "Rest before lift");
    if lift_mm > 0.0 {
        line(move_to(z_mm + lift_mm, lift_speed, "Z Lift (1)"));
        wait(&mut line, after_lift_s, "Wait after lift");

        // The plate has to stand at this layer's own Z before the light goes on, so a
        // retract shorter than the lift is followed by a second move down to it. The two
        // distances are compared rather than the positions, which differ by a float step
        // when the retract matches the lift exactly.
        if retract_mm < lift_mm {
            line(move_to(
                z_mm + lift_mm - retract_mm,
                retract_speed,
                "Retract (1)",
            ));
            line(move_to(z_mm, retract_speed, "Retract (2)"));
        } else {
            line(move_to(z_mm, retract_speed, "Retract (1)"));
        }
        wait(&mut line, after_retract_s, "Wait after retract");
    } else {
        line(move_to(z_mm, lift_speed, "Move Z"));
    }

    wait(&mut line, material.light_off_s(), "Wait before cure");
    line(format!("M106 S{pwm};Turn LED ON\n"));
    line(format!(
        "G4 P{};Cure time/delay\n",
        ms(job.exposure_of_layer_s(index))
    ));
    block.push_str("M106 S0;Turn LED OFF\n;<Slice> Blank\n;LAYER_END\n\n");
    block
}

/// The closing moves: the last layer peeled off the film, then the plate out of the vat.
pub(crate) fn epilogue(job: &PrintJob) -> String {
    let material = &job.material;
    let top_mm = job.height_mm();
    let machine_z = job.printer.build_volume.z;
    let lifted = (top_mm + material.lift_distance_mm).min(machine_z.max(top_mm));

    let mut text = ";START_GCODE_END\nM106 S0;Turn LED OFF\n".to_owned();
    if lifted > top_mm {
        text.push_str(&move_to(lifted, material.lift_speed_mm_min, "Z Lift (1)"));
    }
    if machine_z > lifted {
        text.push_str(&move_to(machine_z, material.lift_speed_mm_min, "Move Z"));
    }
    text.push_str("M18;Disable motors\n;END_GCODE_END\n;<Completed>\n");
    text
}

/// What the layer at `index` is called inside the archive. The numbering starts at one.
pub(crate) fn image_name(index: u32) -> String {
    format!("{}.png", index + 1)
}

/// One absolute move of the plate, millimetres at millimetres a minute.
fn move_to(z_mm: f32, speed_mm_min: f32, comment: &str) -> String {
    format!("G0 Z{} F{};{comment}\n", mm(z_mm), mm(speed_mm_min))
}

/// A `G4` dwell, written only where there is something to wait for.
fn wait(line: &mut impl FnMut(String), seconds: f32, comment: &str) {
    if seconds > 0.0 {
        line(format!("G4 P{};{comment}\n", ms(seconds)));
    }
}

/// Seconds as the whole milliseconds a `G4 P` takes.
fn ms(seconds: f32) -> u32 {
    (seconds * 1000.0).round().max(0.0) as u32
}

/// A number to the micron and no further, without the trailing zeros a `{}` would leave.
fn mm(value: f32) -> String {
    let text = format!("{value:.3}");
    let text = text.trim_end_matches('0').trim_end_matches('.');
    if text.is_empty() { "0" } else { text }.to_owned()
}

/// A `;key:value` header, in the order the keys were added.
#[derive(Default)]
struct Header {
    lines: String,
}

impl Header {
    fn text(&mut self, key: &str, value: &str) {
        self.lines.push(';');
        self.lines.push_str(key);
        self.lines.push(':');
        self.lines.push_str(value);
        self.lines.push('\n');
    }

    fn int(&mut self, key: &str, value: u32) {
        self.text(key, &value.to_string());
    }

    fn number(&mut self, key: &str, value: f32) {
        self.text(key, &mm(value));
    }

    fn finish(self) -> String {
        self.lines
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fixtures::sample_job;
    use core_format::{ExposurePlan, ExposureRange};
    use printer_profiles::{WaitMode, Waits};

    fn value_of<'a>(gcode: &'a str, key: &str) -> Option<&'a str> {
        gcode
            .lines()
            .find_map(|line| line.strip_prefix(&format!(";{key}:")))
    }

    #[test]
    fn the_header_states_the_stack_the_blocks_go_on_to_run() {
        let job = sample_job(12);
        let text = preamble(&job);

        assert_eq!(value_of(&text, "totalLayer"), Some("12"));
        assert_eq!(value_of(&text, "resolutionX"), Some("8"));
        assert_eq!(value_of(&text, "machineType"), Some("Test"));
        assert_eq!(
            value_of(&text, "bottomLayExposureTime"),
            value_of(&text, "bottomLayerExposureTime"),
            "both keys carry the bottom exposure, for either generation of a reader"
        );
        assert_eq!(value_of(&text, "mirror"), Some("0"));
        assert_eq!(value_of(&text, "projectType"), Some("Normal"));
        assert!(text.contains("\nG90;Absolute positioning\n"));
    }

    #[test]
    fn a_mirrored_panel_says_so_in_both_places_a_reader_looks() {
        let mut job = sample_job(1);
        job.printer.mirror_x = true;
        let text = preamble(&job);

        assert_eq!(value_of(&text, "mirror"), Some("1"));
        assert_eq!(value_of(&text, "projectType"), Some("LCD_mirror"));
    }

    #[test]
    fn a_layer_shows_its_image_then_peels_and_cures_at_its_own_z() {
        let mut job = sample_job(3);
        job.material.bottom_layers = 0;
        job.material.exposure_s = 2.5;
        job.material.lift_distance_mm = 5.0;
        job.material.retract_distance_mm = 5.0;
        job.material.lift_speed_mm_min = 60.0;
        job.material.retract_speed_mm_min = 150.0;
        job.material.light_off_delay_s = 0.5;
        let z = job.layer_z_mm(1);

        let block = layer_block(&job, 1);
        let lines: Vec<&str> = block.lines().collect();
        assert_eq!(
            lines,
            vec![
                ";LAYER_START:1",
                ";PositionZ:0.1mm",
                "M6054 \"2.png\";Show image",
                &format!("G0 Z{} F60;Z Lift (1)", mm(z + 5.0)),
                "G0 Z0.1 F150;Retract (1)",
                "G4 P500;Wait before cure",
                "M106 S255;Turn LED ON",
                "G4 P2500;Cure time/delay",
                "M106 S0;Turn LED OFF",
                ";<Slice> Blank",
                ";LAYER_END",
                "",
            ]
        );
    }

    #[test]
    fn a_retract_shorter_than_the_lift_still_ends_at_the_layers_own_z() {
        let mut job = sample_job(2);
        job.material.bottom_layers = 0;
        job.material.lift_distance_mm = 6.0;
        job.material.retract_distance_mm = 4.0;
        let block = layer_block(&job, 0);
        let z = mm(job.layer_z_mm(0));

        assert!(
            block.contains(&format!("G0 Z{} F", mm(job.layer_z_mm(0) + 2.0))),
            "the retract covers its own 4 mm of the 6 mm lift: {block}"
        );
        assert!(
            block.contains(&format!(
                "G0 Z{z} F{};Retract (2)",
                mm(job.material.retract_speed_mm_min)
            )),
            "a second move brings the plate down to {z} mm before the light goes on"
        );
    }

    #[test]
    fn a_retract_matching_the_lift_is_one_move_and_not_two() {
        let mut job = sample_job(2);
        job.material.bottom_layers = 1;
        job.material.bottom_lift_distance_mm = 8.0;
        job.material.lift_distance_mm = 6.0;
        job.material.retract_distance_mm = 6.0;

        // The bottom layer retracts by its own lift distance, so neither layer needs two
        // moves — and z + d - d is a float step above z, which must not make one.
        for index in 0..2 {
            let block = layer_block(&job, index);
            assert!(
                !block.contains("Retract (2)"),
                "layer {index} comes down in one move: {block}"
            );
        }
    }

    #[test]
    fn the_bottom_block_peels_and_cures_on_its_own_numbers() {
        let mut job = sample_job(4);
        job.material.bottom_layers = 2;
        job.material.bottom_exposure_s = 30.0;
        job.material.bottom_lift_distance_mm = 7.0;
        job.material.bottom_lift_speed_mm_min = 40.0;
        job.material.bottom_light_pwm = 200;
        job.material.transition_layers = 0;

        let first = layer_block(&job, 0);
        assert!(first.contains("F40;Z Lift (1)"));
        assert!(first.contains("M106 S200;Turn LED ON"));
        assert!(first.contains("G4 P30000;Cure time/delay"));

        let third = layer_block(&job, 2);
        assert!(!third.contains("F40;Z Lift (1)"));
        assert!(third.contains("M106 S255;Turn LED ON"));
    }

    #[test]
    fn a_band_of_height_reaches_the_layer_it_covers() {
        let mut job = sample_job(6);
        job.material.bottom_layers = 0;
        job.material.layer_height_mm = 1.0;
        job.plan = core_format::LayerPlan::of_count(1.0, 6);
        job.exposure = ExposurePlan::new(vec![ExposureRange::new(3.0, 5.0, 7.0)]);

        assert!(layer_block(&job, 3).contains("G4 P7000;Cure time/delay"));
        assert!(!layer_block(&job, 5).contains("G4 P7000;Cure time/delay"));
    }

    #[test]
    fn a_resting_resin_gets_its_three_rests_around_the_peel() {
        let mut job = sample_job(2);
        job.material.lift_distance_mm = 5.0;
        job.material.waits = Waits {
            mode: WaitMode::Rest,
            before_lift_s: 1.0,
            after_lift_s: 0.5,
            after_retract_s: 2.0,
        };
        let block = layer_block(&job, 0);

        assert!(block.contains("G4 P1000;Rest before lift"));
        assert!(block.contains("G4 P500;Wait after lift"));
        assert!(block.contains("G4 P2000;Wait after retract"));
        assert!(
            !block.contains("Wait before cure"),
            "a resin that rests holds no light-off delay"
        );
    }

    #[test]
    fn the_program_ends_with_the_plate_out_of_the_vat() {
        let job = sample_job(4);
        let text = epilogue(&job);

        assert!(text.contains("M106 S0;Turn LED OFF"));
        assert!(
            text.contains(&format!("G0 Z{} F", mm(job.printer.build_volume.z))),
            "the plate comes up to the top of the travel so the part can be taken off"
        );
        assert!(text.ends_with("M18;Disable motors\n;END_GCODE_END\n;<Completed>\n"));
    }
}
